name: starpy
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  path_provider: ^2.0.11
  starflut:
    path: ../
  # starflut:
  #   git:
  #     url: https://github.com/rohitsangwan01/starcore_for_flutter.git
  #     ref: null_safe

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

get_cli:
  sub_folder: false

flutter:
  uses-material-design: true
  assets:
    - starfiles/
    - starfiles/main.py
